// React_Js/src/React_Application/SkinCare/src/Payment.js


import React, { useState } from 'react';
import { useCart } from './CartContext';
import './Payment.css';

const Payment = () => {
  const { cart, clearCart } = useCart();
  const [selectedPaymentMethod, setSelectedPaymentMethod] = useState('credit');
  const [formValues, setFormValues] = useState({
    cardNumber: '',
    validThru: '',
    cvv: '',
    upiId: ''
  });
  const [errors, setErrors] = useState({});

  // Calculate total amount
  const totalAmount = cart.reduce((total, item) => total + item.price * item.quantity, 0);

  // Function to validate form inputs
  const validateForm = () => {
    const newErrors = {};

    if (selectedPaymentMethod === 'credit') {
      if (!/^[0-9]{16}$/.test(formValues.cardNumber)) {
        newErrors.cardNumber = 'Card Number must be 16 digits';
      }
      if (!/^(0[1-9]|1[0-2])\/?([0-9]{2})$/.test(formValues.validThru)) {
        newErrors.validThru = 'Valid Thru must be in MM/YY format';
      }
      if (!/^[0-9]{3}$/.test(formValues.cvv)) {
        newErrors.cvv = 'CVV must be 3 digits';
      }
    } else if (selectedPaymentMethod === 'upi' && !formValues.upiId) {
      newErrors.upiId = 'UPI ID is required';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // Handle payment method change
  const handlePaymentMethodChange = (method) => {
    setSelectedPaymentMethod(method);
    setErrors({});
    setFormValues({
      cardNumber: '',
      validThru: '',
      cvv: '',
      upiId: ''
    });
  };

  // Handle input changes
  const handleChange = (e) => {
    setFormValues({
      ...formValues,
      [e.target.name]: e.target.value
    });
  };

  // Handle form submission
  const handleSubmit = (e) => {
    e.preventDefault();
    if (validateForm()) {
      placeOrder();
    }
  };

  // Function to place an order
  const placeOrder = () => {
    const deliveryDate = new Date();
    deliveryDate.setDate(deliveryDate.getDate() + 7);

    const orderDetails = {
      items: cart,
      totalAmount: totalAmount,
      paymentMethod: selectedPaymentMethod === 'credit' ? 'Credit/Debit/ATM Card' : selectedPaymentMethod === 'upi' ? 'UPI' : 'Cash on Delivery',
      deliveryDate: deliveryDate,
      orderDate: new Date()
    };

    console.log('Order placed:', orderDetails);
    clearCart();
    // Navigate to order success page or display a success message
  };

  return (
    <div className="payment-container">
      <h2>Payment</h2>
      <form onSubmit={handleSubmit}>
        <div className="form-group-radio">
          <label>
            <input
              type="radio"
              value="credit"
              checked={selectedPaymentMethod === 'credit'}
              onChange={() => handlePaymentMethodChange('credit')}
            />
            Credit/Debit/ATM Card
          </label>
          <label>
            <input
              type="radio"
              value="upi"
              checked={selectedPaymentMethod === 'upi'}
              onChange={() => handlePaymentMethodChange('upi')}
            />
            UPI
          </label>
          <label>
            <input
              type="radio"
              value="cod"
              checked={selectedPaymentMethod === 'cod'}
              onChange={() => handlePaymentMethodChange('cod')}
            />
            Cash on Delivery
          </label>
        </div>

        {selectedPaymentMethod === 'credit' && (
          <div className="credit-form">
            <div className="form-group">
              <label htmlFor="cardNumber">Card Number</label>
              <input
                id="cardNumber"
                name="cardNumber"
                type="text"
                value={formValues.cardNumber}
                onChange={handleChange}
              />
              {errors.cardNumber && <small className="error">{errors.cardNumber}</small>}
            </div>
            <div className="form-group">
              <label htmlFor="validThru">Valid Thru (MM/YY)</label>
              <input
                id="validThru"
                name="validThru"
                type="text"
                value={formValues.validThru}
                onChange={handleChange}
              />
              {errors.validThru && <small className="error">{errors.validThru}</small>}
            </div>
            <div className="form-group">
              <label htmlFor="cvv">CVV</label>
              <input
                id="cvv"
                name="cvv"
                type="text"
                value={formValues.cvv}
                onChange={handleChange}
              />
              {errors.cvv && <small className="error">{errors.cvv}</small>}
            </div>
            <button type="submit">Pay ₹{totalAmount}</button>
          </div>
        )}

        {selectedPaymentMethod === 'upi' && (
          <div className="upi-form">
            <div className="form-group">
              <label htmlFor="upiId">UPI ID</label>
              <input
                id="upiId"
                name="upiId"
                type="text"
                value={formValues.upiId}
                onChange={handleChange}
              />
              {errors.upiId && <small className="error">{errors.upiId}</small>}
            </div>
            <button type="submit">Pay ₹{totalAmount}</button>
          </div>
        )}

        {selectedPaymentMethod === 'cod' && (
          <div className="cod-form">
            <button type="submit">Place Order</button>
          </div>
        )}
      </form>
    </div>
  );
};

export default Payment;

// Angularjs/OnlineShop/src/app/payment/payment.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { Router,RouterModule } from '@angular/router';
import { CartService } from '../cart.service';

@Component({
  selector: 'app-payment',
  standalone: true,
  imports: [ReactiveFormsModule, CommonModule],
  templateUrl: './payment.component.html',
  styleUrls: ['./payment.component.css']
})
export class PaymentComponent {
  paymentForm: FormGroup;
  selectedPaymentMethod: string = 'credit';
  items = this.cartService.getItems();
  totalAmount: number = this.items.reduce((total, item) => total + item.price * item.quantity, 0);

  constructor(private fb: FormBuilder, private cartService: CartService, private router: Router) {
    this.paymentForm = this.fb.group({
      cardNumber: ['', [Validators.required, Validators.pattern(/^[0-9]{16}$/)]],
      validThru: ['', [Validators.required, Validators.pattern(/^(0[1-9]|1[0-2])\/?([0-9]{2})$/)]],
      cvv: ['', [Validators.required, Validators.pattern(/^[0-9]{3}$/)]],
      upiId: ['', Validators.required]
    });
  }

  onPaymentMethodChange(method: string) {
    this.selectedPaymentMethod = method;
  }

  // onSubmit() {
  //   if (this.selectedPaymentMethod === 'credit' && this.paymentForm.valid) {
  //     alert('Order successfully placed using Credit/Debit/ATM Card');
  //     // Proceed with order placement logic
  //   } else if (this.selectedPaymentMethod === 'upi') {
  //     alert('Order successfully placed using UPI');
  //     // Proceed with order placement logic
  //   } else if (this.selectedPaymentMethod === 'cod') {
  //     alert('Order successfully placed with Cash on Delivery');
  //     // Proceed with order placement logic
  //   }
  //   this.router.navigate(['/ordersuccess']);
  
     
      
  // }



  onSubmit() {
    if (this.selectedPaymentMethod === 'credit' && this.paymentForm.valid) {
      this.placeOrder('Credit/Debit/ATM Card');
    } else if (this.selectedPaymentMethod === 'upi') {
      this.placeOrder('UPI');
    } else if (this.selectedPaymentMethod === 'cod') {
      this.placeOrder('Cash on Delivery');
    }
  }

  placeOrder(paymentMethod: string) {
    const deliveryDate = new Date();
    deliveryDate.setDate(deliveryDate.getDate() + 7);

    const orderDetails = {
      items: this.items,
      totalAmount: this.totalAmount,
      paymentMethod: paymentMethod,
      deliveryDate: deliveryDate,
      orderDate: new Date()
    };

    this.cartService.setOrderDetails(orderDetails);
    this.router.navigate(['/ordersuccess']);
  }
}

<div class="payment-container">
    <h2>Payment</h2>
    
    <form [formGroup]="paymentForm" (ngSubmit)="onSubmit()">
      <div class="form-group-radio">
        <label>
          <input type="radio" value="credit" (change)="onPaymentMethodChange('credit')" [checked]="selectedPaymentMethod === 'credit'">
          Credit/Debit/ATM Card
        </label>
        <label>
          <input type="radio" value="upi" (change)="onPaymentMethodChange('upi')" [checked]="selectedPaymentMethod === 'upi'">
          UPI
        </label>
        <label>
          <input type="radio" value="cod" (change)="onPaymentMethodChange('cod')" [checked]="selectedPaymentMethod === 'cod'">
          Cash on Delivery
        </label>
      </div>
  
      <div *ngIf="selectedPaymentMethod === 'credit'" class="credit-form">
        <div class="form-group">
          <label for="cardNumber">Card Number</label>
          <input id="cardNumber" formControlName="cardNumber" type="text" />
          <div *ngIf="paymentForm.get('cardNumber')?.invalid && (paymentForm.get('cardNumber')?.dirty || paymentForm.get('cardNumber')?.touched)">
            <small class="error" *ngIf="paymentForm.get('cardNumber')?.errors?.['required']">Card Number is required</small>
            <small class="error" *ngIf="paymentForm.get('cardNumber')?.errors?.['pattern']">Card Number must be 16 digits</small>
          </div>
        </div>
        <div class="form-group">
          <label for="validThru">Valid Thru (MM/YY)</label>
          <input id="validThru" formControlName="validThru" type="text" />
          <div *ngIf="paymentForm.get('validThru')?.invalid && (paymentForm.get('validThru')?.dirty || paymentForm.get('validThru')?.touched)">
            <small class="error" *ngIf="paymentForm.get('validThru')?.errors?.['required']">Valid Thru is required</small>
            <small class="error" *ngIf="paymentForm.get('validThru')?.errors?.['pattern']">Valid Thru must be in MM/YY format</small>
          </div>
        </div>
        <div class="form-group">
          <label for="cvv">CVV</label>
          <input id="cvv" formControlName="cvv" type="text" />
          <div *ngIf="paymentForm.get('cvv')?.invalid && (paymentForm.get('cvv')?.dirty || paymentForm.get('cvv')?.touched)">
            <small class="error" *ngIf="paymentForm.get('cvv')?.errors?.['required']">CVV is required</small>
            <small class="error" *ngIf="paymentForm.get('cvv')?.errors?.['pattern']">CVV must be 3 digits</small>
          </div>
        </div>
        <button type="submit" [disabled]="paymentForm.invalid">Pay ₹{{ totalAmount }}</button>
      </div>
  
      <div *ngIf="selectedPaymentMethod === 'upi'" class="upi-form">
        <div class="form-group">
          <label for="upiId">UPI ID</label>
          <input id="upiId" formControlName="upiId" type="text" />
          <div *ngIf="paymentForm.get('upiId')?.invalid && (paymentForm.get('upiId')?.dirty || paymentForm.get('upiId')?.touched)">
            <small class="error" *ngIf="paymentForm.get('upiId')?.errors?.['required']">UPI ID is required</small>
          </div>
        </div>
        <button type="submit" [disabled]="paymentForm.invalid">Pay ₹{{ totalAmount }}</button>
      </div>
  
      <div *ngIf="selectedPaymentMethod === 'cod'" class="cod-form">
        <button type="submit">Place Order</button>
      </div>
    </form>
  </div>
